name: third action


env:
  cloud: 'cloud_engineer'

on:
  push:
 
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  shell_script_command:
      runs-on: ubuntu-latest
      
      steps:
          - name: run basic hello world command
            run: echo 'hello world, i am grateful to be a $cloud'
     
               
    
          - name: run a simple hello script to test this code
            run: |
                 touch index2.txt
                 echo > i am doing well
 
